version: "3.2"
services:
  database:
    container_name: database
    image: mariadb
    volumes:
      - ~/db/conf.d:/etc/mysql/conf.d:ro
      - ~/db/data:/var/lib/mysql
      - ~/db/logs:/var/log/maria
    environment:
      - MYSQL_DATABASE=database_name
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306

  application:
    build: ./app
    ports:
      - 8080:8080
    depends_on:
      - database