spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/rtdc?serverTimezone=Asia/Seoul
    username: root
    password: password
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      #use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true